<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bookstore.Data</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RootNamespace>Bookstore.Data</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties/AssemblyInfo.cs"></Compile>
  </ItemGroup>
  <ItemGroup>
    <Compile Exclude="bin\**;obj\**;Properties\AssemblyInfo.cs" Include="**\*.cs"></Compile>
  </ItemGroup>
  <ItemGroup>
    <None Condition="'Library' == 'Exe'" Include="App.config"></None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\"></Folder>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="*"></PackageReference>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.10.2"></PackageReference>
    <PackageReference Include="AWSSDK.Core" Version="4.0.3.11"></PackageReference>
    <PackageReference Include="AWSSDK.Rekognition" Version="4.0.3.13"></PackageReference>
    <PackageReference Include="AWSSDK.S3" Version="4.0.18.2"></PackageReference>
    <PackageReference Include="EntityFramework" Version="6.5.1"></PackageReference>
    <PackageReference Include="Magick.NET.Core" Version="14.9.0"></PackageReference>
  </ItemGroup>
</Project>