<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bookstore.Cdk</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <OutputType>Exe</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RootNamespace>Bookstore.Cdk</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Exclude="bin\**;obj\**;Properties\AssemblyInfo.cs" Include="**\*.cs"></Compile>
  </ItemGroup>
  <ItemGroup>
    <None Condition="'Exe' == 'Exe'" Include="App.config"></None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\"></Folder>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.CDK.AWS.ECS" Version="1.204.0"></PackageReference>
    <PackageReference Include="Amazon.CDK.AWS.ElasticLoadBalancingV2" Version="1.204.0"></PackageReference>
    <PackageReference Include="Amazon.CDK.AWS.RDS" Version="1.204.0"></PackageReference>
    <PackageReference Include="Amazon.CDK.AWS.IAM" Version="1.204.0"></PackageReference>
    <PackageReference Include="Amazon.CDK.AWS.Cognito" Version="1.204.0"></PackageReference>
    <PackageReference Include="Amazon.CDK" Version="1.204.0"></PackageReference>
    <PackageReference Include="Amazon.CDK.AWS.CloudFront" Version="1.204.0"></PackageReference>
    <PackageReference Include="Amazon.CDK.AWS.S3" Version="1.204.0"></PackageReference>
    <PackageReference Include="Amazon.CDK.AWS.SSM" Version="1.204.0"></PackageReference>
  </ItemGroup>
</Project>